### ISSUE TITLE
"Hint" argument to Field() class

### ISSUE THREAD

**Issue by Rudedog9d** [ameily/cincoconfig#36]
Feature Idea: Add a "hint" argument to the field() class that stores information about what the config option does. Two possible uses:

- Set the function docstring to this value for evaluation within the application
- Write out a comment before the value in configuration files for formats that support it (ex, yaml) Example:

```py
from cincoconfig import *

# first, define the configuration's schema -- the fields available that
# customize the application's or library's behavior
schema = Schema()
schema.mode = ApplicationModeField(
    default='production', hint="Mode of application Operation. Development mode enables additional logging and features."
)

# ...

# set a config value manually
if config.mode == 'production':
    config.db.name = config.db.name + '_production'

print(config.dumps(format='yaml', hints=True).decode())
```
```yml
db:
  host: localhost
  name: my_app_production
  password: null
  port: 27017
  user: null
http:
  address: 127.0.0.1
  port: 8080
  ssl:
    cafile: null
    certfile: null
    enabled: false
    keyfile: null
# Mode of application Operation. Development mode enables additional logging and features.
mode: production
```
